# Welcome to Serverless!

service: helloworld

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  stage: ${opt:stage}
  memorySize: 1536 # optional, default is 1024
  timeout: 30 # timeout in seconds
  description: seagull helloworld example app
  iamRoleStatements: ${file(./config/iam_roles.js):${opt:stage}}
  environment: ${file(./config/environments.js):${opt:stage}}
  apiKeys:
    # - ${self:service}_${self:provider.stage}

package:
  include:
    - dist/*
    - config/**

plugins:
  - serverless-prune-plugin
  - serverless-apigw-binary

custom:
  prune:
    automatic: true
    number: 3

  # actually: https://medium.com/@smspillaz/getting-aws-lambda-and-api-gateway-to-support-binary-2018-edition-9dfd81ab9291
  apigwBinary:
    types: #list of mime-types
      # - 'image/jpeg'
      # - 'image/png'
      # - 'text/html'
      - '*/*'

functions:
  lambda: ${file(./dist/assets/backend/lambda.js):${opt:stage}}
