# Setup
title:        Seagull Core
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "/seagull"
paginate:     1

# About/contact
author:
  name:       Maximilian Stroh
  url:        https://seagull-js.github.io/seagull/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown