# Setup
title:        'Seagull::Core'
tagline:      Featherweight Zero-Config Typesafe Isomorphic Cloud Framework
baseurl:      "/seagull"

# About/contact
author:
  name:       Maximilian Stroh
  url:        https://seagull-js.github.io/seagull/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown